#!/bin/bash
 
########################
#                      #
# Scheduler Directives #
#                      #
########################
 
### Set the name of the job, where jobname is a unique name for your job
#PBS -N test_vec
 
### Select the shell you would like the script to execute within
#PBS -S /bin/bash
 
### Inform the scheduler of the expected runtime, where walltime=DD:HH:MM:SS
#PBS -l walltime=00:02:00:00
 
### Inform the scheduler of the number of CPU cores for your job.
### This example will allocate four cores on a single node.
#PBS -l nodes=2:ppn=1
 
### Inform the scheduler of the amount of memory you expect to use.
### Use units of 'b', 'kb', 'mb', or 'gb'
#PBS -l mem=2gb
 
### Set the destination for your program's output.
#PBS -o $HOME/stratification-data_analysis/logs/test_vec.out
#PBS -e $HOME/stratification-data_analysis/logs/test_vec.err
 
### Change working directory to the one it was submitted from
cd $PBS_O_WORKDIR

#################
#               #
# Job Execution #
#               #
#################
 
# Load the appropriate applications
module load gcc/6.2.0
module load plink/2.00a3LM
module load openssl/1.1.1d
module load python/3.7.6
 
# Execute the program
snakemake --cores all
