---
title: "Check_Samples"
author: "Jennifer Blanc"
date: "7/8/2022"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
rm(list=ls())
library(data.table)
library(tidyverse)
```


```{r}
# Read in sample file from Xin's group
sample_file <- fread("../output/transfer/ukb27386_imp_v3_s487324.sample.gz")
sample_file <- sample_file[2:nrow(sample_file),] 

# Read in height file from our data
height <- fread("../output/transfer/standing_height_50.txt.gz")
height <- height %>% select("50-0.0", "50-1.0") 
colnames(height) <- c("eid", "height")

# Read in genetic sex file from our data 
gsex <- fread("../output/transfer/genetic_sex_22001.txt.gz")
gsex <- gsex %>% select("22001-0.0", "V3")
colnames(gsex) <- c("eid", "sex")
```

```{r}
# Merge sample and genetic sex file
df <- inner_join(sample_file, gsex, by=c("ID_1" = "eid"))

# Merge height and genetic sex
df2 <- inner_join(height, gsex)
```

```{r}
## Compute TGWAS

X1 <- matrix(rbinom(200*100, 2, 0.5), nrow = 100, ncol = 200)
X1 <- scale(X1, scale = F)
X2 <- matrix(rbinom(200*100, 2, 0.5), nrow = 100, ncol = 200)
X2 <- scale(X2, scale = F)

G1 <- matrix(rbinom(200*150, 2, 0.5), nrow = 150, ncol = 200)
G1 <- scale(G1, scale = F)
G2 <- matrix(rbinom(200*150, 2, 0.5), nrow = 150, ncol = 200)
G2 <- scale(G2, scale = F)

Tvec <- 10 * runif(100)
Tvec <- Tvec - mean(Tvec) 

Tm1 <- G1 %*% t(X1) %*% Tvec 
Tm2 <- G2 %*% t(X2) %*% Tvec

X <- cbind(X1, X2)
G <- cbind(G1, G2)

Tm <- G %*% t(X) %*% Tvec  
Tm_chr <- Tm1 + Tm2
```

